version = 1

[install]
livereload.pkg-path = "python313Packages.livereload"
imagemagick.pkg-path = "imagemagick"
pngquant.pkg-path = "pngquant"
optipng.pkg-path = "optipng"
libwebp.pkg-path = "libwebp"
just.pkg-path = "just"
google-lighthouse.pkg-path = "google-lighthouse"
google-lighthouse.systems = ["aarch64-linux", "x86_64-linux"]
nodejs.pkg-path = "nodejs"

[hook]
on-activate = """
echo ""
echo "To start the livereload server, run the following command:"
echo "    $ livereload --port 8888"
echo ""
"""

[services]
livereload.command = """
livereload --port 8888
"""

