version = 1

[install]
livereload.pkg-path = "python313Packages.livereload"
nodejs.pkg-path = "nodejs"

[hook]
on-activate = """
# TODO: print how to start livereload
"""

[services]
livereload.command = """
livereload
"""

