version = 1

[install]
livereload.pkg-path = "python313Packages.livereload"

[hook]
on-activate = """
echo ""
echo "To start the livereload server, run the following command:"
echo "    $ livereload --port 8888"
echo ""
"""

[services]
livereload.command = """
livereload --port 8888
"""

