version = 1

[install]
livereload.pkg-path = "python313Packages.livereload"
imagemagick.pkg-path = "imagemagick"
pngquant.pkg-path = "pngquant"
optipng.pkg-path = "optipng"
libwebp.pkg-path = "libwebp"

[hook]
on-activate = """
echo ""
echo "To start the livereload server, run the following command:"
echo "    $ livereload --port 8888"
echo ""
"""

[services]
livereload.command = """
livereload --port 8888
"""

